//cart constants
export const ADD_TO_CART_PENDING = 'ADD_TO_CART_PENDING';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILED='ADD_TO_CART_FAILED';

export const REMOVE_FROM_CART_PENDING = 'REMOVE_FROM_CART_PENDING';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_SUCCESS';
export const REMOVE_FROM_CART_FAILED='REMOVE_FROM_FAILED';

export const ADD_TO_GUEST_CART='ADD_TO_GUEST_CART';
export const REMOVE_FROM_GUEST_CART='REMOVE_FROM_GUEST_CART';

export const LOAD_CART='LOAD_CART';
export const SEARCH_PRODUCT='SEARCH_PRODUCT';
export const CHANGE_SEARCH_FIELD='CHANGE_SEARCH_FIELD';

export const SEARCH_PRODUCT_PENDING='SEARCH_PRODUCT_PENDING';
export const SEARCH_PRODUCT_SUCCESS='SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAILED='SEARCH_PRODUCT_FAILED';

export const REQUEST_PRODUCT_PENDING='REQUEST_PRODUCT_PENDING';
export const REQUEST_PRODUCT_SUCCESS='REQUEST_PRODUCT_SUCCESS';
export const REQUEST_PRODUCT_FAILED='REQUEST_PRODUCT_FAILED';

export const REGISTER_USER='REGISTER_USER';

export const LOGIN_USER_PENDING='LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED='LOGIN_USER_FAILED';


export const REGISTER_USER_PENDING='REGISTER_USER_PENDING';
export const REGISTER_USER_SUCCESS='REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED='REGISTER_USER_FAILED';

export const LOGOUT_USER_PENDING='LOGOUT_USER_PENDING';
export const LOGOUT_USER_SUCCESS='LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILED='LOGOUT_USER_FAILED';

export const USER_NOT_SIGNED_IN='USER_NOT_SIGNED_IN';
export const EMPTY_CART='EMPTY_CART';

export const CHECKOUT_FROM_ITEM='CHECKOUT_FROM_ITEM';
export const CHECKOUT_FROM_CART='CHECKOUT_FROM_CART';
export const CHECKOUT='CHECKOUT';